# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# Book settings
# -------------
title: Orgaaninen kemia
author: <a href="https://luma-lapinamk.pub">LUMA-team</a> (<a href="mailto:luma@lapinamk.fi">luma@lapinamk.fi</a>), <a href="https://www.lapinamk.fi/en">Lapland University of Applied Sciences</a> / Minna Korhonen (<a href="mailto:minna.korhonen@lapinamk.fi">minna.korhonen@lapinamk.fi</a>) ja Miika Aitomaa (<a href="mailto:miika.aitomaa@lapinamk.fi">miika.aitomaa@lapinamk.fi</a>)

copyright: "2022"
logo: \images\logo.png

# Execution settings
# -------------------
execute:
  execute_notebooks: force

# GitHub-settings
# ----------------
repository:
  url: https://github.com/luma-lapinamk/miika-orgkemia
  branch: main

# HTML-settings
# --------------
html:
  use_issues_button: false
  use_repository_button: true
  extra_navbar: <a href="https://jupyterbook.org">Jupyter Book</a> voimaa

